logo: images/ferris-waving.png
title: A technical report on RRB-Tree based vector for Rust
theme: jekyll-theme-minimal
exclude:
  - main.tex
  - refs.bib
  - chapters/
  - forside/
  - data/
  - build.sh
  - settings.json
  - wrangler.jsonc
  - Gemfile
